### ISSUE TITLE
Usage with Spring Boot 2.2.0 causes ClassNotFoundException

### ISSUE THREAD

**Issue by nt-jj** [microsoft/spring-cloud-azure#576]
## Expected Behavior
* Usage with Spring Boot 2.2.x does not cause a ClassNotFoundException

## Current Behavior
* Usage with Spring Boot 2.2.x does cause a ClassNotFoundException
Stacktrace:
```
Caused by: java.lang.IllegalStateException: Failed to introspect Class [org.springframework.cloud.stream.config.BinderFactoryConfiguration] from ClassLoader [org.springframework.boot.loader.LaunchedURLClassLoader@7c729a55]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:477)
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:355)
	at org.springframework.util.ReflectionUtils.getUniqueDeclaredMethods(ReflectionUtils.java:411)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.lambda$getTypeForFactoryMethod$2(AbstractAutowireCapableBeanFactory.java:743)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryMethod(AbstractAutowireCapableBeanFactory.java:742)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:681)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:649)
	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1605)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:520)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:491)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:613)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:605)
	at org.springframework.boot.context.TypeExcludeFilter.getDelegates(TypeExcludeFilter.java:77)
	at org.springframework.boot.context.TypeExcludeFilter.match(TypeExcludeFilter.java:65)
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.isCandidateComponent(ClassPathScanningCandidateComponentProvider.java:492)
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.scanCandidateComponents(ClassPathScanningCandidateComponentProvider.java:431)
	... 30 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/springframework/integration/handler/support/HandlerMethodArgumentResolversHolder
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2309)
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:459)
	... 46 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.integration.handler.support.HandlerMethodArgumentResolversHolder
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:92)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 50 common frames omitted
```
After a downgrade to spring boot 2.1.9 it works again. The missing class was deprecated is no longer available if you use spring boot 2.2.0

## Steps to Reproduce (for bugs)
* Having an application working with spring boot 2.1.9
* switch to spring boot 2.2.0
* start application
* see above ClassNotFoundException during start up

**Comment by neuqlz** [comment]
Yep, nowadays spring-cloud-azure is not compatible with spring-boot:2.2.x, we will release a new version later, in the version, it will work.

**Comment by nt-jj** [comment]
Do you know already in which version, you want to support 2.2.x?

**Comment by saragluna** [comment]
@nt-jj What did you mean by which version?  The version will be something like 1.2.x which will align with Spring Cloud Hoxton and Spring Boot 2.2.x.

**Comment by nt-jj** [comment]
That was actually the answer I was looking for. Thanks for that.

**Comment by nt-jj** [comment]
From my point of view this issue is solved. I just tested it with version 1.2.1 and so far it works fine. Just like @saragluna stated in here comment.

Or is there a reason why this issue is still open?

**Comment by neuqlz** [comment]
This issue can be closed.
